server:
  port: 9210

spring:
  application:
    name: App
  profiles:
    active: dev
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://47.103.204.17:3306/zlg_shop?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: zlg
    password: 47b94fe43cc858ee
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: work.ambitlu.*.model
  global-config:

    #刷新mapper 调试神器
    banner: false
    db-config:
      table-underline: false #驼峰下划线转换
      id-type: assign_id  #主键类型  UUID
      update-strategy: not_empty  #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
