server:
  port: 9210

spring:
  application:
    name: App
  datasource:
    url: jdbc:mysql://175.24.12.207:3306/zlg_shop?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: zlg
    password: 47b94fe43cc858ee
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: work.ambitlu
  global-config:

    #刷新mapper 调试神器
    banner: false
    db-config:
      table-underline: false #驼峰下划线转换
      id-type: assign_id  #主键类型  UUID
      update-strategy: not_empty  #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
