server:
  port: 9211
spring:
  datasource:
    url: jdbc:mysql://175.24.12.207:3306/zlg_shop?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: zlg
    password: 47b94fe43cc858ee
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-test-query: select 1
  cache:
    type: redis
    redis:
      cache-null-values: true
  redis:
    redisson:
      config: classpath:redisson.yml


